In [1]:
# Dependencies
import pandas as pd
from pathlib import Path

In [5]:
# Load csvs 
csv_path_oct2020 = Path("202010-citibike-tripdata.csv")
df_oct = pd.read_csv(csv_path_oct2020, encoding="utf-8")

csv_path_nov2020 = Path("202011-citibike-tripdata.csv")
df_nov = pd.read_csv(csv_path_nov2020, encoding="utf-8")

csv_path_dec2020 = Path("202012-citibike-tripdata.csv")
df_dec = pd.read_csv(csv_path_dec2020, encoding="utf-8")

In [3]:
df_oct.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1403,2020-10-01 00:00:10.7870,2020-10-01 00:23:34.5400,224,Spruce St & Nassau St,40.711464,-74.005524,3347,Van Brunt St & Wolcott St,40.677343,-74.012751,39079,Subscriber,1995,1
1,462,2020-10-01 00:00:18.2390,2020-10-01 00:08:00.5710,3161,W 76 St & Columbus Ave,40.780184,-73.977285,3158,W 63 St & Broadway,40.771639,-73.982614,41267,Subscriber,1998,2
2,770,2020-10-01 00:00:21.3070,2020-10-01 00:13:12.0840,354,Emerson Pl & Myrtle Ave,40.693631,-73.962236,3761,Cedar St & Myrtle Ave,40.697842,-73.926241,47398,Customer,1996,1
3,233,2020-10-01 00:00:25.0080,2020-10-01 00:04:18.6410,3141,1 Ave & E 68 St,40.765005,-73.958185,464,E 56 St & 3 Ave,40.759345,-73.967597,36482,Subscriber,1993,1
4,126,2020-10-01 00:00:25.3100,2020-10-01 00:02:32.1330,335,Washington Pl & Broadway,40.729039,-73.994046,229,Great Jones St,40.727434,-73.993790,45319,Subscriber,1989,1

In [6]:
df_nov.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,521,2020-11-01 00:00:07.0150,2020-11-01 00:08:48.3010,3467,W Broadway & Spring St,40.724947,-74.001659,350,Clinton St & Grand St,40.715595,-73.987030,40405,Subscriber,1989,1
1,492,2020-11-01 00:00:10.8080,2020-11-01 00:08:23.3170,3557,40 Ave & 9 St,40.757420,-73.945133,3557,40 Ave & 9 St,40.757420,-73.945133,46504,Subscriber,1970,2
2,1979,2020-11-01 00:00:14.7040,2020-11-01 00:33:14.1640,3085,Roebling St & N 4 St,40.714690,-73.957390,3854,Morgan Ave & Maspeth Ave,40.716657,-73.936370,37452,Subscriber,1989,2
3,2382,2020-11-01 00:00:14.7070,2020-11-01 00:39:57.0030,3783,Cliff St & Fulton St,40.708380,-74.004950,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,40417,Subscriber,1981,1
4,166,2020-11-01 00:00:15.9690,2020-11-01 00:03:02.8980,422,W 59 St & 10 Ave,40.770513,-73.988038,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,35776,Subscriber,1990,1

In [7]:
df_dec.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,694,2020-12-01 00:00:03.7770,2020-12-01 00:11:38.3160,4065,Wadsworth Ave & W 179 St,40.848467,-73.936064,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,49454,Customer,1988,2
1,4131,2020-12-01 00:00:09.1730,2020-12-01 01:09:00.2370,3284,E 88 St & Park Ave,40.781411,-73.955959,3147,E 85 St & 3 Ave,40.778012,-73.954071,49524,Subscriber,1988,1
2,1368,2020-12-01 00:00:28.7470,2020-12-01 00:23:16.9980,3443,W 52 St & 6 Ave,40.761330,-73.979820,3563,28 St & 36 Ave,40.757186,-73.932719,34312,Subscriber,1977,2
3,1707,2020-12-01 00:00:34.7680,2020-12-01 00:29:02.6470,72,W 52 St & 11 Ave,40.767272,-73.993929,3336,E 97 St & Madison Ave,40.787801,-73.953559,45491,Subscriber,1982,0
4,2182,2020-12-01 00:00:36.4030,2020-12-01 00:36:59.0330,3165,Central Park West & W 72 St,40.775794,-73.976206,3952,E 141 St & Jackson Ave,40.806896,-73.911837,16558,Customer,1997,1

In [8]:
# Combine dfs
combined_df = pd.concat([df_oct, df_nov, df_dec], ignore_index=True)
combined_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1403,2020-10-01 00:00:10.7870,2020-10-01 00:23:34.5400,224,Spruce St & Nassau St,40.711464,-74.005524,3347,Van Brunt St & Wolcott St,40.677343,-74.012751,39079,Subscriber,1995,1
1,462,2020-10-01 00:00:18.2390,2020-10-01 00:08:00.5710,3161,W 76 St & Columbus Ave,40.780184,-73.977285,3158,W 63 St & Broadway,40.771639,-73.982614,41267,Subscriber,1998,2
2,770,2020-10-01 00:00:21.3070,2020-10-01 00:13:12.0840,354,Emerson Pl & Myrtle Ave,40.693631,-73.962236,3761,Cedar St & Myrtle Ave,40.697842,-73.926241,47398,Customer,1996,1
3,233,2020-10-01 00:00:25.0080,2020-10-01 00:04:18.6410,3141,1 Ave & E 68 St,40.765005,-73.958185,464,E 56 St & 3 Ave,40.759345,-73.967597,36482,Subscriber,1993,1
4,126,2020-10-01 00:00:25.3100,2020-10-01 00:02:32.1330,335,Washington Pl & Broadway,40.729039,-73.994046,229,Great Jones St,40.727434,-73.993790,45319,Subscriber,1989,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5074497,2045,2020-12-31 23:58:21.7040,2021-01-01 00:32:27.1570,526,E 33 St & 5 Ave,40.747659,-73.984907,3614,Crescent St & 30 Ave,40.768692,-73.924957,36467,Subscriber,1994,1
5074498,288,2020-12-31 23:58:37.8400,2021-01-01 00:03:26.3250,3307,West End Ave & W 94 St,40.794165,-73.974124,3383,Cathedral Pkwy & Broadway,40.804213,-73.966991,47749,Subscriber,1969,0
5074499,152,2020-12-31 23:58:52.8090,2021-01-01 00:01:25.6720,3510,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3518,Lenox Ave & W 126 St,40.808442,-73.945209,48691,Customer,1969,0
5074500,654,2020-12-31 23:59:55.9550,2021-01-01 00:10:50.6050,4073,W 51 St & Rockefeller Plaza,40.759700,-73.978082,500,Broadway & W 51 St,40.762288,-73.983362,49564,Subscriber,1994,1
5074501,2589,2020-12-31 23:59:57.4070,2021-01-01 00:43:06.4490,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47364,Customer,1969,0

In [9]:
# Update gender values 
gender_mapping = {0: "Unknown", 1: "Male", 2:"Female"}
combined_df["gender"] = combined_df["gender"].map(gender_mapping)
combined_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1403,2020-10-01 00:00:10.7870,2020-10-01 00:23:34.5400,224,Spruce St & Nassau St,40.711464,-74.005524,3347,Van Brunt St & Wolcott St,40.677343,-74.012751,39079,Subscriber,1995,Male
1,462,2020-10-01 00:00:18.2390,2020-10-01 00:08:00.5710,3161,W 76 St & Columbus Ave,40.780184,-73.977285,3158,W 63 St & Broadway,40.771639,-73.982614,41267,Subscriber,1998,Female
2,770,2020-10-01 00:00:21.3070,2020-10-01 00:13:12.0840,354,Emerson Pl & Myrtle Ave,40.693631,-73.962236,3761,Cedar St & Myrtle Ave,40.697842,-73.926241,47398,Customer,1996,Male
3,233,2020-10-01 00:00:25.0080,2020-10-01 00:04:18.6410,3141,1 Ave & E 68 St,40.765005,-73.958185,464,E 56 St & 3 Ave,40.759345,-73.967597,36482,Subscriber,1993,Male
4,126,2020-10-01 00:00:25.3100,2020-10-01 00:02:32.1330,335,Washington Pl & Broadway,40.729039,-73.994046,229,Great Jones St,40.727434,-73.993790,45319,Subscriber,1989,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5074497,2045,2020-12-31 23:58:21.7040,2021-01-01 00:32:27.1570,526,E 33 St & 5 Ave,40.747659,-73.984907,3614,Crescent St & 30 Ave,40.768692,-73.924957,36467,Subscriber,1994,Male
5074498,288,2020-12-31 23:58:37.8400,2021-01-01 00:03:26.3250,3307,West End Ave & W 94 St,40.794165,-73.974124,3383,Cathedral Pkwy & Broadway,40.804213,-73.966991,47749,Subscriber,1969,Unknown
5074499,152,2020-12-31 23:58:52.8090,2021-01-01 00:01:25.6720,3510,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3518,Lenox Ave & W 126 St,40.808442,-73.945209,48691,Customer,1969,Unknown
5074500,654,2020-12-31 23:59:55.9550,2021-01-01 00:10:50.6050,4073,W 51 St & Rockefeller Plaza,40.759700,-73.978082,500,Broadway & W 51 St,40.762288,-73.983362,49564,Subscriber,1994,Male
5074501,2589,2020-12-31 23:59:57.4070,2021-01-01 00:43:06.4490,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47364,Customer,1969,Unknown

In [ ]:
# Save to csv file 
combined_df.to_csv("combined_citibike_data.csv", encoding="utf-8", index=False, header=True)